name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-latest, macos-latest]
        node-version: [
          1.x,
          2.x,
          3.x,
          4.x,
          5.x,
          6.x,
          7.x,
          8.x,
          9.x,
          10.x,
          11.x,
          12.x,
          13.x,
          14.x,
          15.x,
          16.x,
        ]
    steps:
    - uses: actions/checkout@v1
    - name: ${{ matrix.os }} | ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
    - name: Test Module
      run: |
        coffee test.coffee
      env:
        CI: true
